server:
  port: 8081
spring:
  application:
    name: eureka-server-8081
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-server-8080:8080/eureka/,http://eureka-server-8082:8082/eureka/
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-server-8081
    instance-id: eureka-server-8081
    non-secure-port: 8081
    prefer-ip-address: false
  server:
    enable-self-preservation: false #禁用eureka-server的自我保护机制