server:
  port: 8080
spring:
  application:
    name: eureka-server-8080
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-server-8081:8081/eureka/,http://eureka-server-8082:8082/eureka/
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka-server-8080
    instance-id: eureka-server-8080
    non-secure-port: 8080 #端口
    prefer-ip-address: false  #访问的地址是否变成ip地址
  server:
    enable-self-preservation: false #是否启用自我保护机制