server:
  port: 7071
spring:
  application:
    name: eureka-client-7071
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.39.21.4:3306/se-cim?useUnicode=true&characterEncoding=UTF8
    password: se-CIM-2017
    username: secim2017
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-server-8080:8080/eureka/,http://eureka-server-8081:8081/eureka/,http://eureka-server-8082:8082/eureka/
    fetch-registry: true #是否从注册中心中获取注册信息
    register-with-eureka: true #是否向注册中心中进行注册
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: eureka-clien-7071  # 在信息列表时显示主机名称
    prefer-ip-address: false # 访问的路径变为IP地址
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: fnw.cloud.eurekaclient7070.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.fnw.boss.config.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

